// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZKAKUkAcBSAi3x0c4moysYekCo3WMTDo',
    appId: '1:637805349115:web:0a2c8cf75422d5d5cdc85e',
    messagingSenderId: '637805349115',
    projectId: 'test-gemini-c7b7c',
    authDomain: 'test-gemini-c7b7c.firebaseapp.com',
    storageBucket: 'test-gemini-c7b7c.appspot.com',
    measurementId: 'G-GS5B2K4VGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7TSS5vBvRqrT04L2EfjIA210jKfStk0k',
    appId: '1:637805349115:android:24819bd138c15e48cdc85e',
    messagingSenderId: '637805349115',
    projectId: 'test-gemini-c7b7c',
    storageBucket: 'test-gemini-c7b7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS-V_E1wqhfkJ_mvj_TCYQ9gbQJb66zWA',
    appId: '1:637805349115:ios:6e740a4e814b4543cdc85e',
    messagingSenderId: '637805349115',
    projectId: 'test-gemini-c7b7c',
    storageBucket: 'test-gemini-c7b7c.appspot.com',
    androidClientId: '637805349115-jac5a7gqhkea0cpq6sipusla1kbg4r4g.apps.googleusercontent.com',
    iosClientId: '637805349115-j94i9ivenehmmadpbr9kf44avfif5aj3.apps.googleusercontent.com',
    iosBundleId: 'com.example.geminiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS-V_E1wqhfkJ_mvj_TCYQ9gbQJb66zWA',
    appId: '1:637805349115:ios:6e740a4e814b4543cdc85e',
    messagingSenderId: '637805349115',
    projectId: 'test-gemini-c7b7c',
    storageBucket: 'test-gemini-c7b7c.appspot.com',
    androidClientId: '637805349115-jac5a7gqhkea0cpq6sipusla1kbg4r4g.apps.googleusercontent.com',
    iosClientId: '637805349115-j94i9ivenehmmadpbr9kf44avfif5aj3.apps.googleusercontent.com',
    iosBundleId: 'com.example.geminiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZKAKUkAcBSAi3x0c4moysYekCo3WMTDo',
    appId: '1:637805349115:web:55f70b67bafdce75cdc85e',
    messagingSenderId: '637805349115',
    projectId: 'test-gemini-c7b7c',
    authDomain: 'test-gemini-c7b7c.firebaseapp.com',
    storageBucket: 'test-gemini-c7b7c.appspot.com',
    measurementId: 'G-VKJCG67DMQ',
  );

}